language: node_js
node_js:
  - "node"
  - "7"
install:
  - npm install
jobs:
  include:
    - stage: linting
      if: type = pull_request
      script: node ./bin/lint-my-pr.js --slug=${TRAVIS_PULL_REQUEST_BRANCH} --pr=${TRAVIS_PULL_REQUEST}
